print("Meu\nnome\né\nGil")
print("Meu\nnome\né\nGil", end = " Lucas ")
print("Lucas Gil.")
print("peixe", "chips", sep="&")
print("2")
print(2)
print(0x123)
print(0.0000000000000000000001)
print("Eu gosto \"Monty Python\"")
print('I like "Monty Python"')
print('I\'m Monty Python.')
